version: '3.4'

services:
  cardo-project:
    image: ${DOCKER_REGISTRY-}cardoproject
    build:
      context: .
      dockerfile: Cardo-Project/Dockerfile
    volumes:
      - ./Cardo-Project/appsettings.Docker.json:/app/appsettings.json
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker   

  sqlserver:
    container_name: "SQL-Server"
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-volume:/var/opt/mssql

volumes:
    mssql-volume: